[project]
name = "ntcss-scripts"
version = "1.0.0"
description = "Work scripts used with NTCSS linux servers"
requires-python = ">=3.9"
authors = [
    {name = "jshernandez05", email = "<jshernandez05@gmail.com>"},
    ]
readme = "README.md"

[tool.black]
line-length = 120
target-version = ["py26"]